[workspace]
authors = ["Justin Bois <bois@caltech.edu>"]
channels = ["conda-forge"]
name = "distribution-explorer-app"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
black = ">=25.1.0,<26"
bokeh = ">=3.7.3,<4"
colorcet = ">=3.1.0,<4"
ipython = ">=9.4.0,<10"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.5,<5"
jupyter_bokeh = ">=4.0.5,<5"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
pandoc = ">=3.7.0.2,<4"
pip = ">=25.2,<26"
scipy = ">=1.16.0,<2"
sphinx = ">=8.2.3,<9"
sphinxcontrib-applehelp = ">=2.0.0,<3"
sphinxcontrib-devhelp = ">=2.0.0,<3"
sphinxcontrib-htmlhelp = ">=2.1.0,<3"
sphinxcontrib-jsmath = ">=1.0.1,<2"
sphinxcontrib-qthelp = ">=2.0.0,<3"
sphinxcontrib-serializinghtml = ">=1.1.10,<2"
twine = ">=6.1.0,<7"

[pypi-dependencies]
accessible-pygments = ">=0.0.5, <0.0.6"
blackcellmagic = ">=0.0.2, <0.0.3"
build = ">=1.3.0, <2"
commonmark = ">=0.9.1, <0.10"
jupyterlab-spellchecker = ">=0.8.4, <0.9"
iqplot = ">=0.3.7, <0.4"
markdown-it-py = "*"
myst-nb = ">=1.3.0, <2"
myst-parser = ">=4.0.1, <5"
nbsphinx = ">=0.9.6, <0.10"
pydata-sphinx-theme = ">=0.16.1, <0.17"
recommonmark = ">=0.7.1, <0.8"
sphinx-book-theme = ">=1.1.3, <2"
sphinx-comments = ">=0.0.3, <0.0.4"
sphinx-copybutton = ">=0.5.2, <0.6"
sphinx-design = ">=0.6.1, <0.7"
sphinx-external-toc = ">=1.0.1, <2"
sphinx-jupyterbook-latex = ">=1.0.0, <2"
sphinx-multitoc-numbering = ">=0.1.3, <0.2"
sphinx-rtd-theme = ">=3.0.2, <4"
sphinx-thebe = ">=0.3.1, <0.4"
sphinx-togglebutton = ">=0.3.2, <0.4"
sphinxcontrib-jquery = ">=4.1, <5"
watermark = ">=2.5.0, <3"
distribution-explorer = {path = "../distribution-explorer", editable = true}
